# Author: crifan
# Date: 2012-05-16
#
# -----------------------------------------------------------------
#  generate output from DocBook sources
#  this is entry makefile for docbook
# -----------------------------------------------------------------
# run this makefile under src directory:
# [office]
# pwd = /home/CLi/develop/docbook/books/xxx/src
# [home]
# pwd = /cygdrive/e/Dev_Root/docbook/dev/books/xxx/src

################################################################################
# Project Settings
################################################################################

# also means main source file name
PROJECT_NAME = web_scrape_emulate_login
SUB_SRC_FILES = \
    preface.xml \
    ch01_scrape_common_logic.xml \
    ch02_scrape_static_website.xml \
    ch03_emulate_login.xml \
    ch04_scrape_dynamic_website.xml \
    ch05_summary_and_note.xml \
    reference.xml \

DOCBOOK_MAKEFILE_ROOT = ../../../config
################################################################################
# Include docbook makefile
################################################################################
include $(DOCBOOK_MAKEFILE_ROOT)/docbook.mk